Models/AnthonyRodriguez_tabla1.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Examen.Models
{
    
    public class AnthonyRodriguez_tabla1
    {
        [Key]
        public int arCedula { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 7)]
        public string? arNombre { get; set; }

        public bool arEstudiante { get; set; }
        [Range(1.00 , 3.00)]
        public decimal arEstatura { get; set; }

        DateTime fechaActual = new DateTime(2023, 10, 25, 7, 32, 00);
    }

}

Models/ErrorViewModel.cs
namespace Examen.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AnthonyRodriguez_tablas1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Examen.Data;
using Examen.Models;

namespace Examen.Controllers
{
    public class AnthonyRodriguez_tablas1Controller : Controller
    {
        private readonly ExamenContext _context;

        public AnthonyRodriguez_tablas1Controller(ExamenContext context)
        {
            _context = context;
        }

        // GET: AnthonyRodriguez_tablas1
        public async Task<IActionResult> Index()
        {
              return _context.AnthonyRodriguez_tabla1 != null ? 
                          View(await _context.AnthonyRodriguez_tabla1.ToListAsync()) :
                          Problem("Entity set 'ExamenContext.AnthonyRodriguez_tabla1'  is null.");
        }

        // GET: AnthonyRodriguez_tablas1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AnthonyRodriguez_tabla1 == null)
            {
                return NotFound();
            }

            var anthonyRodriguez_tabla1 = await _context.AnthonyRodriguez_tabla1
                .FirstOrDefaultAsync(m => m.arCedula == id);
            if (anthonyRodriguez_tabla1 == null)
            {
                return NotFound();
            }

            return View(anthonyRodriguez_tabla1);
        }

        // GET: AnthonyRodriguez_tablas1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AnthonyRodriguez_tablas1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("arCedula,arNombre,arEstudiante,arEstatura")] AnthonyRodriguez_tabla1 anthonyRodriguez_tabla1)
        {
            if (ModelState.IsValid)
            {
                _context.Add(anthonyRodriguez_tabla1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(anthonyRodriguez_tabla1);
        }

        // GET: AnthonyRodriguez_tablas1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AnthonyRodriguez_tabla1 == null)
            {
                return NotFound();
            }

            var anthonyRodriguez_tabla1 = await _context.AnthonyRodriguez_tabla1.FindAsync(id);
            if (anthonyRodriguez_tabla1 == null)
            {
                return NotFound();
            }
            return View(anthonyRodriguez_tabla1);
        }

        // POST: AnthonyRodriguez_tablas1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("arCedula,arNombre,arEstudiante,arEstatura")] AnthonyRodriguez_tabla1 anthonyRodriguez_tabla1)
        {
            if (id != anthonyRodriguez_tabla1.arCedula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anthonyRodriguez_tabla1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnthonyRodriguez_tabla1Exists(anthonyRodriguez_tabla1.arCedula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(anthonyRodriguez_tabla1);
        }

        // GET: AnthonyRodriguez_tablas1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AnthonyRodriguez_tabla1 == null)
            {
                return NotFound();
            }

            var anthonyRodriguez_tabla1 = await _context.AnthonyRodriguez_tabla1
                .FirstOrDefaultAsync(m => m.arCedula == id);
            if (anthonyRodriguez_tabla1 == null)
            {
                return NotFound();
            }

            return View(anthonyRodriguez_tabla1);
        }

        // POST: AnthonyRodriguez_tablas1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AnthonyRodriguez_tabla1 == null)
            {
                return Problem("Entity set 'ExamenContext.AnthonyRodriguez_tabla1'  is null.");
            }
            var anthonyRodriguez_tabla1 = await _context.AnthonyRodriguez_tabla1.FindAsync(id);
            if (anthonyRodriguez_tabla1 != null)
            {
                _context.AnthonyRodriguez_tabla1.Remove(anthonyRodriguez_tabla1);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnthonyRodriguez_tabla1Exists(int id)
        {
          return (_context.AnthonyRodriguez_tabla1?.Any(e => e.arCedula == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using Examen.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Examen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AnthonyRodriguez_tablas1/Create.cshtml
@model Examen.Models.AnthonyRodriguez_tabla1

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AnthonyRodriguez_tabla1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="arNombre" class="control-label"></label>
                <input asp-for="arNombre" class="form-control" />
                <span asp-validation-for="arNombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="arEstudiante" /> @Html.DisplayNameFor(model => model.arEstudiante)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="arEstatura" class="control-label"></label>
                <input asp-for="arEstatura" class="form-control" />
                <span asp-validation-for="arEstatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AnthonyRodriguez_tablas1/Delete.cshtml
@model Examen.Models.AnthonyRodriguez_tabla1

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnthonyRodriguez_tabla1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arEstatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arEstatura)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="arCedula" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/AnthonyRodriguez_tablas1/Details.cshtml
@model Examen.Models.AnthonyRodriguez_tabla1

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AnthonyRodriguez_tabla1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arEstatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arEstatura)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.arCedula">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/AnthonyRodriguez_tablas1/Edit.cshtml
@model Examen.Models.AnthonyRodriguez_tabla1

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AnthonyRodriguez_tabla1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="arCedula" />
            <div class="form-group">
                <label asp-for="arNombre" class="control-label"></label>
                <input asp-for="arNombre" class="form-control" />
                <span asp-validation-for="arNombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="arEstudiante" /> @Html.DisplayNameFor(model => model.arEstudiante)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="arEstatura" class="control-label"></label>
                <input asp-for="arEstatura" class="form-control" />
                <span asp-validation-for="arEstatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AnthonyRodriguez_tablas1/Index.cshtml
@model IEnumerable<Examen.Models.AnthonyRodriguez_tabla1>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.arNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.arEstudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.arEstatura)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.arNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.arEstudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.arEstatura)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.arCedula">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.arCedula">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.arCedula">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Examen Anthony Rodriguez Progreso 1";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Examen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Examen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AnthonyRodriguez_tablas1">AnthonyRodriguez tabla1</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Examen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>